import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/NavBar'
import Intro from '../components/intro/intro'
import MyProjects from '../components/Myprojects/Myprojects'
import MySkills from '../components/MySkills/MySkills'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
    <div className="app">
    <div className="square">
    <Nav />
    <Intro />
    </div>
    
    <MyProjects />
    
    <MySkills />
    </div>
    <Footer />
    </>
    </div>
  )
}
